### ISSUE TITLE
Spot Checker Workload Sampling

### ISSUE THREAD

**Issue by odobenuskr** [ddps-lab/spot-checker#1]
### 목표
Spot Checker Workload Sampling 기준을 명확하게 정의하고, 해당 기준을 고려한 Sampling 코드 개발 과정을 기록합니다

---

### 공정한 Sampling 기준 및 제약사항
- 다양한 Instance Family 가 포함될 것
- 다양한 Instance Size 가 포함될 것
- 다양한 Region, Availability Zone 이 포함될 것
- 전체 최대 비용이 $5,000 을 넘지 않도록 구성할 것
- 실험을 2회로 분할하여 진행하며, 각 실험 사이의 시간 간격(3~7일)이 존재하게 구성

---

### 추가 고려사항
- Sampling 과정에서 SPS-IF Score 를 고려해야 하는가?
- 분할된 각각의 실험에서 workload 는 동일해야 하는가? 혹은 모두 달라야 하는가? 혹은 절반은 같고 절반은 다르게 구성해야 하는가?
- Sampling 결과에 대해서 중복 검사를 시행했는가? Sampling 은 어떤 분포를 따르는 것이 더 좋은가? 좋은 분포에 기반하여 Sampling 품질을 평가할 수 있는가?

**Comment by odobenuskr** [comment]
### Categorical Sampling 을 위한 InstanceClass, Family, Region, AZ 별 워크로드 분포 확인

Instance Class
![download](https://user-images.githubusercontent.com/20024627/176986577-681a2db3-426b-437f-b973-a0bf9779ac31.png)

Instance Family
![download-1](https://user-images.githubusercontent.com/20024627/176986579-101ea4b1-6d52-4fc5-a1ab-8b20d810cbd4.png)

Region
![download-2](https://user-images.githubusercontent.com/20024627/176986583-34a86225-6a9c-4184-9c4b-421aabe3d346.png)

Availability Zone ID
![download-3](https://user-images.githubusercontent.com/20024627/176986590-942f1a2b-e334-49c9-950d-64aa6fdf527c.png)

이러한 분포를 살펴보았을 때, Categorical Sampling 을 해야 하는 이유는 분포에서 Tail 에 위치한 X, D, Z, INF, P, A, F, H, VT, DL 등의 인스턴스 Class 들이 Random Sampling 으로는 추출되기 어렵고, 대부분 M, R, C 유형만 Sampling 될 것이기 때문입니다. 이는 심각한 Sampling Workload Skew 문제를 발생시키며, 다양한 스팟 인스턴스 자원을 분석하지 못하기 때문에 모델링 결과에 대해서도 제한이 많이 발생할 것입니다.
( 예를 들어 인스턴스 유형 별 Ground Truth 체크 시 문제 발생 )

이는 Region, AZ 에 대해서도 마찬가지이며, Region 의 경우 US-East-1 과 AP-NorthEast-3 가 큰 차이의 Sampling 개수를 보일 수 있습니다.

**Comment by odobenuskr** [comment]
### Cheap Workload Set 의 구성을 통한 Sampling 방안
비용을 고려한 Sampling 을 수행하기 위해서, Cheap Spot Instance 와 Expensive Spot Instance 를 구분하여 Sampling 하는 방법을 고안하였습니다. 이런 아이디어를 생각한 이유는, 저렴한 비용의 Spot Instance 의 경우 많은 실험을 해도 비용에 거의 영향을 미치지 않는 반면, 고비용의 Spot Instance 는 비용에 큰 영향을 미치기 때문입니다.

이에 특정한 Cheap Threshold 를 지정하고 (예를 들어 $0.1, 0.2 ... 0.5 등), 해당 가격보다 저렴한 인스턴스를 모두 나열합니다. $0.1 가격의 인스턴스를 1000종류 실험하면 $2400의 비용이 발생하지만, $1 가격의 인스턴스를 100종류 실험하더라도 동일하게 $2400의 비용이 발생합니다. 하지만 실제 데이터로서 가치는 둘이 크게 차이가 없을 것이라는 생각에 이러한 아이디어를 내었습니다. (물론 저렴한 인스턴스 종류가 많이 추출되어 특정 인스턴스 class 가 많이 나타나는 데이터 skew 의 위험이 있습니다)

아래 그림은 비용이 $0.5 이이하인 인스턴스를 cheap instance set 으로 지정하였을 때, Instance Family 와 Region 을 기준으로 groupby 한 결과입니다. Price 는 해당 조합에서 가장 저렴한 케이스를 추출한 것입니다. 즉, 가장 위의 케이스는 a1 인스턴스 패밀리에서 ap-northeast-1 리전의 가장 저렴한 인스턴스 타입 및 AZ 의 가격이 $0.0086 이라는 것입니다.

<img width="806" alt="image" src="https://user-images.githubusercontent.com/20024627/177033942-faa35c73-9cdf-4a7f-8e00-d863c77ca1cc.png">

이렇게 753 개의 workload 를 추출할 수 있으며, 753개 workload 를 모두 실험했을 때 예상 비용은 최대 $1195.6848 입니다. 즉, 데이터 포인트를 753개 모을 수 있지만 비용은 $1000 로 매우 적다는 것입니다. 이렇게 budget 의 2~30% 의 비용만 cheap workload 에 투자하고, 나머지 비용은 workload 의 balance 를 맞추는 쪽으로 사용한다면 데이터를 많이 수집하는 동시에 분포도 적절한 sampling 이 가능하지 않을까 생각됩니다.

**Comment by kmu-leeky** [comment]
응 성재야. 좋은 생각이다!

**Comment by odobenuskr** [comment]
### Cheap Workload Sampling 시나리오 구조도

<img width="835" alt="image" src="https://user-images.githubusercontent.com/20024627/177081505-b233ec34-dec8-4a6e-820b-7486a6ca9664.png">

---

<img width="772" alt="image" src="https://user-images.githubusercontent.com/20024627/177081520-9a47bd83-9069-4740-8a29-c7d4313669ff.png">

**Comment by odobenuskr** [comment]
### Cheap First, Support After 샘플링 방법
위의 구조도에 이어서, Cheap Workload 는 모두 사용하고, Cheap 에서 선택되지 못한 Category 에 대해서 다시 Expensive Workload 에서 Sampling 하는 방법을 고안하였습니다.
Category 는 Instance Family, Region, SPS-IF Combination 의 세 종류이며, Cheap Workload 를 분석한 결과 Instance Family 에 대해서만 DL1, P3dn, P4d, X1 의 네 종류 Instance Family 가 추출되지 않았습니다. 이는 해당 Instance Family 들 내부의 Instance Type 들이 모두 $1 이상의 비용을 필요로 하기 때문이며, 이러한 이유로 모든 Instance Family 에 대해 실험을 진행하기 위해서는 Expensive Workload 에서 추가적인 Sampling 이 필요합니다.

Expensive Workload 에서 4개 Instance Family 에 대해서 Sampling 할 때, Random Sampling 으로 진행할 경우 많은 수의 GPU 를 보유하는 Instance Type 이 선택되면 매우 높은 비용이 발생합니다. 이러한 이유에서 각 Instance Family 의 가장 저렴한 Instance Type - Region - AZ 조합을 선택하여 4개를 선택하였습니다. 그 결과 해당 인스턴스들에 대해 실험할 경우 4개 데이터 수집 뿐임에도 약 $603 의 비용이 발생합니다. 

여기까지 생각을 해 보니, 앞서 언급한 4개 인스턴스를 꼭 실험해야 하는 것이 아니라면, 오히려 cheap price threshold 를 높여서 더 많은 인스턴스들을 실험할 수 있겠다는 생각도 들었습니다. 만약 threshold 를 $2 로 올린다면, 774개의 데이터 수집이 가능하며, 약 $1586의 비용이 발생합니다.

이전의 실험에서 250개 데이터를 수집하는 데 비용이 많이 들었던 점을 다시 떠올려 보니, 그 때는 Combination 을 과하게 고려하여 size 에 큰 상관 없이 sampling 했기 때문에 비용이 크게 발생한 것으로 생각됩니다. 만약 Combination 을 자연스럽게 추출되도록 하면서, 비용만 고려해 Sampling 한다면 더 많은 데이터 수집이 가능해 보입니다. 

아래는 위의 설명에 대한 구조도입니다.

<img width="1054" alt="image" src="https://user-images.githubusercontent.com/20024627/177275713-44d5c892-cc78-4e4e-9640-c2821f2e30e7.png">

**Comment by odobenuskr** [comment]
### Cheap First, Support After 샘플링 방법
위의 구조도에 이어서, Cheap Workload 는 모두 사용하고, Cheap 에서 선택되지 못한 Category 에 대해서 다시 Expensive Workload 에서 Sampling 하는 방법을 고안하였습니다.
Category 는 Instance Family, Region, SPS-IF Combination 의 세 종류이며, Cheap Workload 를 분석한 결과 Instance Family 에 대해서만 DL1, P3dn, P4d, X1 의 네 종류 Instance Family 가 추출되지 않았습니다. 이는 해당 Instance Family 들 내부의 Instance Type 들이 모두 $1 이상의 비용을 필요로 하기 때문이며, 이러한 이유로 모든 Instance Family 에 대해 실험을 진행하기 위해서는 Expensive Workload 에서 추가적인 Sampling 이 필요합니다.

Expensive Workload 에서 4개 Instance Family 에 대해서 Sampling 할 때, Random Sampling 으로 진행할 경우 많은 수의 GPU 를 보유하는 Instance Type 이 선택되면 매우 높은 비용이 발생합니다. 이러한 이유에서 각 Instance Family 의 가장 저렴한 Instance Type - Region - AZ 조합을 선택하여 4개를 선택하였습니다. 그 결과 해당 인스턴스들에 대해 실험할 경우 4개 데이터 수집 뿐임에도 약 $603 의 비용이 발생합니다. 

여기까지 생각을 해 보니, 앞서 언급한 4개 인스턴스를 꼭 실험해야 하는 것이 아니라면, 오히려 cheap price threshold 를 높여서 더 많은 인스턴스들을 실험할 수 있겠다는 생각도 들었습니다. 만약 threshold 를 $2 로 올린다면, 774개의 데이터 수집이 가능하며, 약 $1586의 비용이 발생합니다.

이전의 실험에서 250개 데이터를 수집하는 데 비용이 많이 들었던 점을 다시 떠올려 보니, 그 때는 Combination 을 과하게 고려하여 size 에 큰 상관 없이 sampling 했기 때문에 비용이 크게 발생한 것으로 생각됩니다. 만약 Combination 을 자연스럽게 추출되도록 하면서, 비용만 고려해 Sampling 한다면 더 많은 데이터 수집이 가능해 보입니다. 

아래는 위의 설명에 대한 구조도입니다.

<img width="1054" alt="image" src="https://user-images.githubusercontent.com/20024627/177275713-44d5c892-cc78-4e4e-9640-c2821f2e30e7.png">

**Comment by odobenuskr** [comment]
### 샘플링 알고리즘 개발 이후 계획
현재 샘플링 알고리즘은 어느 정도 완료가 된 상황이며, 이제 실제 Spot Checker 실험을 위한 준비를 해야합니다.

1. 실제 Spot Checker 작동 시점의 결정 (AWS 의 Credit 논의 완료 이후에 가능)
2. Spot by NetApp 데이터 수집 테스트 (scraping 툴 없이 가능한지 확인 필요)
3. 실험 시점에 workload 확정 및 실험 진행

**Comment by kmu-leeky** [comment]
응 성재야. 내생각에는 굳이 비싼걸 넣지 않더라도 많은 수의 실험을 할 수 있으면 좋을것 같아. 지금 성재가 서술한 방법이 충분히 논리적으로 설명이 가능하다는 생각이 들기도 하고.

실험은 늦어도 목요일에는 시작을 하자. 내일오후까지 기다려보고 연락없으면 목요일에 진행. (너무 늦은가? 내일 오전에 시작해도 괜찮아)
실험을 시작할때 Spot io 데이터는 수집이 되어야 할텐데 수백 종류의 실험이라면 수동으로 수집하기는 무리가 있을것 같고, 코드로 구해오려면 그 시간도 만만치 않겠네. 1차 실험에서만 수동으로 여러명이 체크를 하는것도 방법일것 같아.

2번이 확정되면 3번은 바로 시작을 하면 될것 같아.

**Comment by odobenuskr** [comment]
네 제 생각에도 저렴한 인스턴스를 다양하게 (또는 시간차를 두고 여러 번 반복하여) 실험하는 것이 더 좋아 보입니다. 그러면 1회 실험 예산을 $1000 정도의 비용으로 잡고, 3회 정도 진행하는 것을 목표로 해 보겠습니다.

Spot io 의 경우에는 제가 여러 window 를 띄우고 데이터를 수동으로 긁어오는 것이 가능할 지 한 번 확인해 보고, 너무 어렵다면 selenium 으로 간단히 코드를 작성해 보겠습니다.

**Comment by kmu-leeky** [comment]
셀레니움이 구현이 오래 걸릴것 같으면, 내일 간단히 재일,한정,남궁희,새로운 학생 해서 수동 기록을 해보자.

**Comment by odobenuskr** [comment]
앞서 말씀드린 것에서 한 가지 사항을 더 업데이트 합니다.
Instance Type 과 AZ 정보 또한 아래와 같이 가져올 수 있습니다.

<img width="738" alt="image" src="https://user-images.githubusercontent.com/20024627/177288283-7080e0cf-826c-45e7-96c9-c6237bb0e45a.png">

다음으로 확인해 보아야 하는 것은 아래와 같습니다.
1. 모든 type 을 선택하였을 때 정상적으로 작동하는지 확인
2. type 선택 행위를 selenium 으로 작동시키고, 정보들을 추출할 수 있는지 확인

**Comment by odobenuskr** [comment]
### 확인사항 1. 모든 type 을 선택하였을 때 정상적으로 작동하는지 확인

현재 테스트 중인 지역에서 AZ 는 3종류, Instance Type 은 429 종류입니다.
그러므로 데이터는 중간에 누락(지원하지 않는 type)을 포함하여 3 * 429 = 1287 개가 나타나야 합니다.
그림 우측 하단에 length: 1287 로 모든 데이터를 가져온다는 점을 확인하실 수 있습니다.

<img width="1831" alt="image" src="https://user-images.githubusercontent.com/20024627/177290965-fad08ec7-f784-40bd-ab5a-81c923aa1dd3.png">

<img width="418" alt="image" src="https://user-images.githubusercontent.com/20024627/177291365-c4ee0598-7a7e-4226-9513-7bf08be24e09.png">

Spot 측의 답변으로는 데이터가 몇 시간에 한 번씩 업데이트 된다고 하는데, 최대한 원하는 시점의 데이터를 가져오기 위한 selenium 구현을 테스트 해 보겠습니다. 현재 확인한 것으로는 Instance Type, AZ 선택 클릭에 따라 score 라는 API 가 작동하여, 데이터를 가져오는 것 같습니다. 클릭 동작을 selenium 으로 동일하게 구현하면 문제 없이 crawling 가능할 것으로 보입니다.

**Comment by kmu-leeky** [comment]
아 성재야 잘 찾았다. 저 api 들이 js 로 다 노출되어 있구나. login 이 되기는 해야겠지만 ㅎㅎ 잘찾아냈다. Selemium 으로 구현도 빠르게 잘 진행을 하네 ㅎㅎ 다른 사람 맡기는 것 보다 얼른 해버리는게 빠를것 같기는 하다. 진행하면서 값을 얻어낼수 있도록 해보자 ㅎㅎ

**Comment by odobenuskr** [comment]
실제 Spot Checker 실험은 내일 오전부터 시작 가능할 것 같습니다.
진행 과정은 다음과 같습니다.

- Controller Instance 설정 (지난 200개 실험에서는 c5.12xlarge, 이번에는 750개 실험이므로 더 큰 규모의 controller 가 필요할 수 있음)
- 10개 workload에 대해서 1시간 테스트
- 750개 workload에 대해서 1시간 테스트 (약 $100 사용)
- 750개 workload에 대해서 24시간 실험 진행 (약 $1000 사용)

내일 오전에 Controller 를 설정하고 실험을 시작하도록 하겠습니다.

**Comment by odobenuskr** [comment]
추가 SpotChecker 실험이 완료되었으므로 본 이슈를 close 합니다
