### ISSUE TITLE
GCP spot instance 안정성 테스트 진행

### ISSUE THREAD

**Issue by cg10036** [ddps-lab/spot-checker#3]
GCP spot instance 안정성 테스트를 진행하려 합니다.
먼저 10개를 추려서 테스트하려 하는데 어떤 기준으로 추리면 될까요?

**Comment by kmu-leeky** [comment]
이슈를 만들었네 ㅎㅎ 못봤다 ㅎㅎ #4 에서 인스턴스 타입-region 을 정하는것 부터 시작합시다.
