### ISSUE TITLE
GCP spot instance 체크 모듈 동작 여부 확인을 위한 테스트 진행 시나리오 구성

### ISSUE THREAD

**Issue by kmu-leeky** [ddps-lab/spot-checker#4]
spotlake.ddps.cloud 에서 제공되는 GCP 스팟 인스턴스의 특징 내용을 바탕으로 실험에 사용할 스팟 인스턴스 선정 후 예상대로 진행되는지 확인 필요

선정에 적합한 기준
- 낮은 가격
- 다양한 savings ratio

**Comment by cg10036** [comment]
savings ratio의 현대 최댓값이 91이고 최솟값이 46입니다.

따라서 구간을 다음과 같이 5개로 나누어, 각 구간별로 2개씩 가격이 낮은순으로 뽑아 테스트 진행할 생각입니다.
- 100~85
- 84~75
- 74~65
- 64~55
- 54~0

**Comment by kmu-leeky** [comment]
오케이. 좋은 생각이에요. 어떤 region-instance type 인지 작성해서 공유해주세요.

**Comment by cg10036** [comment]
```
{'InstanceType': 'e2-micro', 'Region': 'europe-central2', 'Preemptible Price': '0.001', 'Savings': '90'}
{'InstanceType': 'e2-micro', 'Region': 'us-west4', 'Preemptible Price': '0.001', 'Savings': '87'}
{'InstanceType': 'n1-standard-1', 'Region': 'asia-east1', 'Preemptible Price': '0.009', 'Savings': '84'}
{'InstanceType': 'n1-standard-1', 'Region': 'asia-southeast1', 'Preemptible Price': '0.009', 'Savings': '84'}
{'InstanceType': 'e2-micro', 'Region': 'us-central1', 'Preemptible Price': '0.003', 'Savings': '70'}
{'InstanceType': 'e2-micro', 'Region': 'us-east1', 'Preemptible Price': '0.003', 'Savings': '70'}
{'InstanceType': 'f1-micro', 'Region': 'us-east4', 'Preemptible Price': '0.004', 'Savings': '57'}
{'InstanceType': 'f1-micro', 'Region': 'us-west4', 'Preemptible Price': '0.004', 'Savings': '57'}
{'InstanceType': 'f1-micro', 'Region': 'us-central1', 'Preemptible Price': '0.004', 'Savings': '54'}
{'InstanceType': 'f1-micro', 'Region': 'us-east1', 'Preemptible Price': '0.004', 'Savings': '54'}
```
구간별로 나눠 정렬해 나온 값입니다. 이대로 진행해도 될까요?

**Comment by cg10036** [comment]
테스트를 위해 GCP에서 'spot-checker'로 프로젝트를 만들었습니다. 해당 프로젝트에 'spot-checker'로 서비스 계정을 생성했습니다.

**Comment by kmu-leeky** [comment]
오케이. 진행하면서 이슈 있으면 공유해주고 결과 로그도 함께 공유해주면 좋을듯해요.

**Comment by kmu-leeky** [comment]
24시간

**Comment by cg10036** [comment]
[logs.zip](https://github.com/ddps-lab/spot-checker/files/9776128/logs.zip)
수집된 로그입니다. f1-micro/us-west4-a와 e2-micro/us-central1-a는 각각 한번씩 종료되었고 나머지는 24시간동안 한번도 중지되지 않았습니다.
<img width="691" alt="스크린샷 2022-10-13 오후 8 33 37" src="https://user-images.githubusercontent.com/30382481/195586125-262440f9-85a1-405b-a2a7-f1d9a098303a.png">
<img width="689" alt="스크린샷 2022-10-13 오후 8 34 14" src="https://user-images.githubusercontent.com/30382481/195586145-f16a85bd-1517-4d03-94a5-99408fa5e563.png">

spotlake.github.io에 gcp 데이터에는 region만 존재하고 zone이 포함되어있지 않으므로, zone은 'a' 혹은 'b'를 사용해 테스트 했습니다. (ex: europe-central2-'a')
