### ISSUE TITLE
Azure 안정성 체크 모듈 구성하기

### ISSUE THREAD

**Issue by kmu-leeky** [ddps-lab/spot-checker#9]
#4 의 GCP 및 aws 폴더의 내용을 참조하여 Azure 용 스팟 인스턴스 실험 동작 모듈 구현하기

**Comment by cg10036** [comment]
아직 Azure는 arm으로 가상 머신을 만들 수 없는것 같습니다. x86으로만 동작하게 작성해도 될까요?

**Comment by kmu-leeky** [comment]
그럼요. x86 만 지원해줘도 괜찮아요.

**Comment by subeans** [comment]
구현 완료된 것 같아 close 합니다.
